### ISSUE TITLE
Visual bugs on Android Chrome

### ISSUE THREAD

**Issue by kettle11** [kettle11/Bloom3D#12]
Android Chrome has very different face colors and a noticeable artifact in shadows. Could it be due to mobile shader precision issues?

**Comment by kettle11** [comment]
Another Android user reported black faces. Related? 

Their phone: Samsung A22 Android 11 using Chrome

**Comment by yinchy** [comment]
I also encountered black faces on Android Chrome

**Comment by kettle11** [comment]
I pushed this an hour ago: https://github.com/kettle11/koi/commit/45000b7406d67798a455946e53d42061c8ccf724

It seems like it fixes shadow artifacts and overly white faces on Android, but *does not* fix the scenario where black faces show up.

**Comment by kettle11** [comment]
A user checked the console and the errors indicated the "OES_texture_float_linear" extension is not supported on their device. Now to investigate how to get around that!

**Comment by kettle11** [comment]
Potentially fixed in https://github.com/kettle11/koi/commit/752672a3d52d57eeb8bfb9a2f7271154d2e51abd and https://github.com/kettle11/koi/commit/805aa4ea4814da14dc98ea1665d64e5ae2fd8738

**Comment by kettle11** [comment]
Confirmed fixed!
