### ISSUE TITLE
Ability to continue working on models even after closing the website 

### ISSUE THREAD

**Issue by karanganesan** [kettle11/Bloom3D#22]
Some ideas 
- Auto save to browser localstorage / indexeddb
- Import exported glb files?

**Comment by karanganesan** [comment]
Auto save is what this issue is like 

related to https://github.com/kettle11/Bloom3D/issues/15

**Comment by kettle11** [comment]
Definitely agree!

This is a high priority. 

An additional concern is where UI like Load / New Model / Save, etc. should go. I can't add a button onscreen every time. Probably some sort of hamburger menu is needed.

**Comment by kettle11** [comment]
Implemented in next release by saving to IndexedDB.

Import will be implemented in a separate release.
